# fly.toml app configuration file generated for caricampsite-frontend on 2023-09-22T07:35:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caricampsite-frontend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
