version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cari_campsite_dev
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
    working_dir: /myapp/backend
    environment:
      PROCESS_TYPE: backend
      EB_ENV: staging
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_NAME: cari_campsite_dev
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      SECRET_KEY_BASE: a8nSg2dWxUPenPgV
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.development
    working_dir: /frontend/app
    volumes:
      - ./frontend:/frontend/app
    environment:
      PROCESS_TYPE: frontend
      API_BASE_URL: http://backend:3000/api/v1
      AUTH_BASE_URL: http://backend:3000/auth
      INTERNAL_BASE_URL: http://backend:3000/internal
      SESSION_SECRET: dwd2rdfi3qjoq
      WATCHPACK_POLLING: true # for hot reload purpose
      CHOKIDAR_USEPOLLING: true # for hot reload purpose
    ports:
      - "3100:3100"
    depends_on:
      - backend
    stdin_open: true
    tty: true

