source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.0.7", ">= 7.0.7.2"
gem 'pg'
gem "puma", "~> 5.0"
gem 'httparty'
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.7"
gem "kaminari", "~> 1.2"
gem "jsonapi-serializer", "~> 2.2"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem "devise"
gem 'doorkeeper', '~> 5.4.0'

# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "dotenv-rails"
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "faker"
end

group :development do
  gem "spring"
end

