const FeatureOption = [
  { id: 1, name: 'tent_camping' },
  { id: 2, name: 'rv_camping' },
  { id: 3, name: 'cabin_rentals' },
  { id: 4, name: 'glamping' },
  { id: 5, name: 'group_camping' },
  { id: 6, name: 'beach_camping' },
  { id: 7, name: 'mountain_camping' },
  { id: 8, name: 'lakefront_camping' },
  { id: 9, name: 'forest_camping' },
  { id: 10, name: 'desert_camping' },
  { id: 11, name: 'backcountry_camping' },
  { id: 12, name: 'family_friendly' },
  { id: 13, name: 'pet_friendly' },
  { id: 14, name: 'boondocking' },
  { id: 15, name: 'fishing_camping' },
  { id: 16, name: 'hunting_camping' },
  { id: 17, name: 'winter_camping' },
  { id: 18, name: 'eco_friendly' },
  { id: 19, name: 'romantic_getaway' },
  { id: 20, name: 'adventure_camping' },
  { id: 21, name: 'off_roading_camping' },
  { id: 22, name: 'solo_camping' },
  { id: 23, name: 'luxury_camping' },
  { id: 24, name: 'historical_camping' },
  { id: 25, name: 'farm_camping' }
];

const AmenityOption = [
  { id: 1, name: 'swimming_pool' },
  { id: 2, name: 'wifi' },
  { id: 3, name: 'restaurant' },
  { id: 4, name: 'playground' },
  { id: 5, name: 'shower_facility' },
  { id: 6, name: 'toilet_facility' },
  { id: 7, name: 'picnic_area' },
  { id: 8, name: 'campfire_area' },
  { id: 9, name: 'hiking_trails' },
  { id: 10, name: 'fishing' },
  { id: 11, name: 'cycling' },
  { id: 12, name: 'boating' },
  { id: 13, name: 'wildlife_viewing' },
  { id: 14, name: 'pet_friendly' },
  { id: 15, name: 'rv_hookups' },
  { id: 16, name: 'electricity_hookups' },
  { id: 17, name: 'laundry_facility' },
  { id: 18, name: 'camp_store' },
  { id: 19, name: 'showers' },
  { id: 20, name: 'restrooms' },
  { id: 21, name: 'dump_station' },
  { id: 22, name: 'picnic_tables' },
  { id: 23, name: 'fire_pits' },
  { id: 24, name: 'barbecue_grills' },
  { id: 25, name: 'drinking_water' }
];

const ActivityOption = [
  { id: 1, name: 'hiking' },
  { id: 2, name: 'biking' },
  { id: 3, name: 'fishing' },
  { id: 4, name: 'boating' },
  { id: 5, name: 'bird_watching' },
  { id: 6, name: 'canoeing' },
  { id: 7, name: 'kayaking' },
  { id: 8, name: 'swimming' },
  { id: 9, name: 'wildlife_viewing' },
  { id: 10, name: 'stargazing' },
  { id: 11, name: 'photography' },
  { id: 12, name: 'rock_climbing' },
  { id: 13, name: 'horseback_riding' },
  { id: 14, name: 'picnicking' },
  { id: 15, name: 'geocaching' },
  { id: 16, name: 'hunting' },
  { id: 17, name: 'campfire' },
  { id: 18, name: 'archery' },
  { id: 19, name: 'nature_programs' },
  { id: 20, name: 'orienteering' },
  { id: 21, name: 'backpacking' },
  { id: 22, name: 'caving' },
  { id: 23, name: 'cross_country_skiing' },
  { id: 24, name: 'snowshoeing' },
  { id: 25, name: 'snowmobiling' },
  { id: 26, name: 'off_roading' },
  { id: 27, name: 'ice_fishing' },
  { id: 28, name: 'sled_dog_mushing' },
  { id: 29, name: 'water_skiing' },
  { id: 30, name: 'wind_surfing' },
  { id: 31, name: 'tubing' }
];

const CategoryOption = [
  { id: 1, name: 'tent_camping' },
  { id: 2, name: 'rv_camping' },
  { id: 3, name: 'cabin_rentals' },
  { id: 4, name: 'glamping' },
  { id: 5, name: 'group_camping' },
  { id: 6, name: 'beach_camping' },
  { id: 7, name: 'mountain_camping' },
  { id: 8, name: 'lakefront_camping' },
  { id: 9, name: 'forest_camping' },
  { id: 10, name: 'desert_camping' },
  { id: 11, name: 'backcountry_camping' },
  { id: 12, name: 'family_friendly' },
  { id: 13, name: 'pet_friendly' },
  { id: 14, name: 'boondocking' },
  { id: 15, name: 'fishing_camping' },
  { id: 16, name: 'hunting_camping' },
  { id: 17, name: 'winter_camping' },
  { id: 18, name: 'eco_friendly' },
  { id: 19, name: 'romantic_getaway' },
  { id: 20, name: 'adventure_camping' },
  { id: 21, name: 'off_roading_camping' },
  { id: 22, name: 'solo_camping' },
  { id: 23, name: 'luxury_camping' },
  { id: 24, name: 'historical_camping' },
  { id: 25, name: 'farm_camping' }
];

const AccessibilityFeatureOption = [
  { id: 1, name: 'wheelchair_accessible' },
  { id: 2, name: 'pet_friendly' },
  { id: 3, name: 'hiking_trails' }
];

export {
  FeatureOption,
  AmenityOption,
  ActivityOption,
  CategoryOption,
  AccessibilityFeatureOption
};
